lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'   
    token_ttl: 3600  
    encoder:
        signature_algorithm: HS256
    user_id_claim: email  # This is the correct option to set the user identity field
    
